# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfiecontest', '0017_auto_20170728_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupfies',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to=b'')),
                ('like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
