# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0018_groupfies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groupfies',
            new_name='GreenVibes',
        ),
    ]
