# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0019_auto_20170806_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenvibes',
            name='image_caption',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picto',
            name='image_caption',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
