# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0020_auto_20170806_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
