# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfiecontest', '0023_auto_20170827_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picto',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
